version: '3'
services:
  db:
    image: mysql:5.7
    container_name: wavelog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password-segreta
    #ports:
    #  - "3306:3306"
    networks:
      - wavelog-net
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wavelog-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: password-segreta
    restart: unless-stopped
    ports:
      - "4081:80"
    networks:
      - wavelog-net

  wavelog:
    image: iu2frl/wavelog:latest
    container_name: wavelog-main
    volumes:
      - config:/var/www/html/application/config
      - backup:/var/www/html/application/backup
      - uploads:/var/www/html/application/uploads
    ports:
      - "4080:80"
    networks:
      - wavelog-net
    restart: unless-stopped

volumes:
  dbdata:
  config:
  backup:
  uploads:

networks:
  wavelog-net:
