version: '3'
services:
  db:
    image: mysql:5.7
    container_name: cloudlog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password-segreta
      MYSQL_USER: cloudlog-user
      MYSQL_PASS: cloudlog-pass
    #ports:
    #  - "3306:3306"
    networks:
      - cloudlog-net
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cloudlog-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: password-segreta
    restart: unless-stopped
    ports:
      - "4083:80"
    networks:
      - cloudlog-net

  cloudlog:
    image: iu2frl/wavelog:latest
    container_name: cloudlog-main
    volumes:
      - cloudlog-config:/var/www/html/application/config
      - cloudlog-backup:/var/www/html/application/backup
      - cloudlog-uploads:/var/www/html/application/uploads
    ports:
      - "4086:80"
    networks:
      - cloudlog-net
    restart: unless-stopped

volumes:
  dbdata:
  cloudlog-config:
  cloudlog-backup:
  cloudlog-uploads:

networks:
  cloudlog-net:
